server:
  port: 8025
  servlet:
#    指定上下文，表示必须在端口号后面加上此路径才能正常访问
    context-path: /api

spring:
  application:
    name: Intelligent-cloud-backend

#    数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/IC_picture
    username: root
    password: 123456

    # 开放更大的文件上传体积
  servlet:
    multipart:
      max-file-size: 10MB
    context-path: /api

  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
    cookie:
      max-age: 2592000


  #  profiles:
#    active: local

  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 5000


mybatis-plus:
  configuration:
#    开启驼峰转化
    map-underscore-to-camel-case: false
#    开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete #逻辑删除的实体字段名
      logic-delete-value: 1 #逻辑已删除值默认为1
      logic-not-delete-value: 0 # 逻辑未删除值默认未0


# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.guanbean.inteligentcloudbackend.controller

